[package]
name = "reizu"
description = "Provides a namespace for reizu crates"
version = "0.1.1"
license = "MIT OR Apache-2.0"
repository = "https://github.com/reizu/reizu_rust"
keywords = ["reizu"]
authors = ["George Moschovitis <gmosx@reizu.org>"]

edition = "2021"

[dependencies]
